# Generated by Django 3.1.2 on 2020-12-03 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='Department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('IT', 'IT')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='Semester',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)]),
        ),
    ]
