# Generated by Django 3.1.2 on 2020-11-30 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('section', '0001_initial'),
        ('time_table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Status', models.CharField(choices=[('P', 'P'), ('A', 'A')], max_length=1)),
                ('Enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
                ('Section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='section.section')),
                ('Subject_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_table.subject')),
            ],
        ),
    ]
