# Generated by Django 3.1.2 on 2020-11-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('Camera_Id', models.CharField(max_length=50)),
                ('Class_Number', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('Section_Name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
