# Generated by Django 3.1.2 on 2020-12-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
    ]
