# Generated by Django 3.1.2 on 2020-12-12 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201203_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Face_Date',
            fields=[
                ('Enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.student')),
                ('Face_Data', models.TextField()),
            ],
        ),
    ]
