# Generated by Django 3.1.2 on 2020-12-16 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_face_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Face_Data',
            fields=[
                ('Enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.student')),
                ('Face_Data', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Face_Date',
        ),
    ]
