# Generated by Django 3.1.2 on 2020-12-16 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20201216_1546'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Face_Data',
            new_name='FaceData',
        ),
    ]
