# Generated by Django 3.1.2 on 2020-12-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20201216_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facedata',
            name='Face_Data',
            field=models.BinaryField(),
        ),
    ]
